# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('docfile', models.FileField(upload_to=b'uploaded')),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('thumb', models.FileField(blank=True, null=True, upload_to=b'uploaded/thumbs')),
                ('kind', models.CharField(choices=[(b'DOCUM', b'Document'), (b'VIDEO', b'Video'), (b'PHOTO', b'Image')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Documentary',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tagline', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Documentaries',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('year_range_end', models.IntegerField(null=True)),
                ('date_format', models.CharField(max_length=10, null=True)),
                ('date_approxQ', models.BooleanField(verbose_name=b'Date is approximate')),
                ('place', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('pointer', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('kind', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Event')),
            ],
        ),
        migrations.CreateModel(
            name='Gedcom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=40, null=True)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
                ('key_families', models.ManyToManyField(blank=True, related_name='gedcom_key_families', to='gedgo.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('pointer', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('gedcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gedgo.Gedcom')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pointer', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('prefix', models.CharField(max_length=255)),
                ('suffix', models.CharField(max_length=255)),
                ('education', models.TextField(null=True)),
                ('religion', models.CharField(blank=True, max_length=255, null=True)),
                ('birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_birth', to='gedgo.Event')),
                ('child_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_child_family', to='gedgo.Family')),
                ('death', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_death', to='gedgo.Event')),
                ('gedcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gedgo.Gedcom')),
                ('notes', models.ManyToManyField(blank=True, to='gedgo.Note')),
                ('profile', models.ManyToManyField(blank=True, to='gedgo.Document')),
                ('spousal_families', models.ManyToManyField(related_name='person_spousal_families', to='gedgo.Family')),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.AddField(
            model_name='gedcom',
            name='key_people',
            field=models.ManyToManyField(blank=True, related_name='gedcom_key_people', to='gedgo.Person'),
        ),
        migrations.AddField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(related_name='family_children', to='gedgo.Person'),
        ),
        migrations.AddField(
            model_name='family',
            name='gedcom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gedgo.Gedcom'),
        ),
        migrations.AddField(
            model_name='family',
            name='husbands',
            field=models.ManyToManyField(related_name='family_husbands', to='gedgo.Person'),
        ),
        migrations.AddField(
            model_name='family',
            name='joined',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_joined', to='gedgo.Event'),
        ),
        migrations.AddField(
            model_name='family',
            name='notes',
            field=models.ManyToManyField(blank=True, to='gedgo.Note'),
        ),
        migrations.AddField(
            model_name='family',
            name='separated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_separated', to='gedgo.Event'),
        ),
        migrations.AddField(
            model_name='family',
            name='wives',
            field=models.ManyToManyField(related_name='family_wives', to='gedgo.Person'),
        ),
        migrations.AddField(
            model_name='event',
            name='gedcom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gedgo.Gedcom'),
        ),
        migrations.AddField(
            model_name='documentary',
            name='gedcom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gedgo.Gedcom'),
        ),
        migrations.AddField(
            model_name='documentary',
            name='tagged_families',
            field=models.ManyToManyField(blank=True, related_name='documentaries_tagged_families', to='gedgo.Family'),
        ),
        migrations.AddField(
            model_name='documentary',
            name='tagged_people',
            field=models.ManyToManyField(blank=True, related_name='documentaries_tagged_people', to='gedgo.Person'),
        ),
        migrations.AddField(
            model_name='documentary',
            name='thumb',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentaries_thumb', to='gedgo.Document'),
        ),
        migrations.AddField(
            model_name='document',
            name='gedcom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gedgo.Gedcom'),
        ),
        migrations.AddField(
            model_name='document',
            name='tagged_families',
            field=models.ManyToManyField(blank=True, related_name='media_tagged_families', to='gedgo.Family'),
        ),
        migrations.AddField(
            model_name='document',
            name='tagged_people',
            field=models.ManyToManyField(blank=True, related_name='media_tagged_people', to='gedgo.Person'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tagged_people',
            field=models.ManyToManyField(blank=True, related_name='blogpost_tagged_people', to='gedgo.Person'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tagged_photos',
            field=models.ManyToManyField(blank=True, related_name='blogpost_tagged_photos', to='gedgo.Document'),
        ),
    ]
